name: Build VI package (ubuntu test)

on:
  workflow_dispatch:

jobs:
  build-vi-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: LabVIEW-Community-CI-CD/labview-icon-editor
          path: labview-icon-editor/labview-icon-editor
      - name: Run build-vi-package action
        uses: ./build-vi-package/action.yml
        with:
          minimum_supported_lv_version: '2021'
          supported_bitness: '64'
          labview_minor_revision: '0'
          relative_path: 'labview-icon-editor/labview-icon-editor'
          vipb_path: 'labview-icon-editor/labview-icon-editor/source/lv_icon.vipb'
          major: '1'
          minor: '0'
          patch: '0'
          build: '1'
          commit: 'abcdef'
          display_information_json: '{"Name":"Test"}'
      - name: Upload VI package
        uses: actions/upload-artifact@v4
        with:
          name: vi-package
          path: 'labview-icon-editor/labview-icon-editor/build/lv_icon.vip'
