name: Missing in project (self-hosted test)

on:
  workflow_dispatch:

jobs:
  missing-in-project:
    runs-on: [self-hosted, icon-editor-windows]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: LabVIEW-Community-CI-CD/labview-icon-editor
          path: ../../labview-icon-editor/labview-icon-editor
      - name: Run missing-in-project action
        uses: ./missing-in-project/action.yml
        with:
          lv_version: '2021'
          arch: '64'
          project_file: 'C:\\actions-runner\\_work\\labview-icon-editor\\labview-icon-editor\\source\\lv_icon.lvproj'
          relative_path: 'C:\\actions-runner\\_work\\labview-icon-editor\\labview-icon-editor'
      - name: Upload missing findings
        uses: actions/upload-artifact@v4
        with:
          name: missing-files
          path: 'C:\\actions-runner\\_work\\open-source-actions\\open-source-actions\\scripts\\missing-in-project\\missing_files.txt'
