name: Release Tests

on:
  release:
    types: [published]

jobs:
  pester-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -Force -Scope CurrentUser

      - name: Run Pester tests
        shell: pwsh
        run: Invoke-Pester -CI -Path tests/pester
